[package]
name = "stava"
version = "0.4.1"
description = "Spell checker"
authors = ["Simon Egersand <s.egersand@gmail.com>"]

repository = "https://github.com/simeg/stava"
homepage = "https://github.com/simeg/stava"
documentation = "https://github.com/simeg/stava/blob/master/README.md"
readme = "README.md"
license = "MIT"
edition = "2018"
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

[dependencies]
clap = { version = "2.31.2", default-features = false }
lazy_static = "1.4.0"
regex = { version = "1.3.1", default-features = false, features = ["std", "perf"] }
include_dir = "0.4.1"
