[package]
name = "stava"
version = "0.2.0"
description = "Spell checker"
authors = ["Simon Egersand <s.egersand@gmail.com>"]

repository = "https://github.com/simeg/stava"
homepage = "https://github.com/simeg/stava"
documentation = "https://github.com/simeg/stava/blob/master/README.md"
readme = "README.md"
license = "MIT"
edition = "2018"
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

[dependencies]
clap = "2.31.2"
lazy_static = "1.4.0"
regex = "1.3.1"
